indexLocale:
    path: /{_locale}/
    defaults: { _controller: TwoMartensContentBundle:Index:index }
    requirements:
        _locale: de|en

index:
    path: /
    defaults: { _controller: TwoMartensContentBundle:Index:index }
    requirements:
        _locale: en
webplatform:
    path: /web-platform/
    defaults: { _controller: TwoMartensContentBundle:Index:webplatform }
talks:
    path: /talks/
    defaults: { _controller: TwoMartensContentBundle:Index:talks }
file:
    path: /file/{name}/
    defaults: { _controller: TwoMartensContentBundle:Index:file }
    requirements:
        name: [a-Z0-9\-_]+